# Generated by Django 2.0 on 2018-12-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['comment']},
        ),
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.IntegerField(max_length=100),
        ),
    ]
