# Generated by Django 2.0 on 2018-12-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20181206_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.IntegerField(),
        ),
    ]
