# Generated by Django 2.0 on 2018-12-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20181206_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_time']},
        ),
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.CharField(max_length=100),
        ),
    ]
